title: Michael Jae-Yoon Chung
email: mjyc@cs.washington.edu
description: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mjyc_
github_username: mjyc
google_analytics: "UA-142528997-1"

markdown: kramdown
theme: minima
plugins:
  - jekyll-scholar
header_pages:
  - index.md
  - research.md
  - blog.md

scholar:
  bibliography_template: "bib"
  repository: "/assets/pdfs"
  sort_by: "year,month"
  order: "descending"
