title: Michael Jae-Yoon Chung
email: mjyc@cs.washington.edu
google_analytics: "G-NZ4FX6FCL4"
utterances:
  repo: "mjyc/mjyc.github.io"

collections:
  notes:
    output: true
    permalink: /notes/:title.html

markdown: kramdown
theme: minima
plugins:
  - jekyll-scholar
header_pages:
  - index.md
  - blog.html
  - notes.html
  - research.md

scholar:
  bibliography_template: "bib"
  repository: "/assets/pdfs"
  sort_by: "year,month"
  order: "descending"
