title: Michael Jae-Yoon Chung
email: mjyc@cs.washington.edu
description: ""
url: ""
twitter_username: mjyc_
github_username: mjyc
google_analytics: "G-NZ4FX6FCL4"

markdown: kramdown
theme: minima
plugins:
  - jekyll-scholar
header_pages:
  - index.md
  - blog.md
  - research.md

scholar:
  bibliography_template: "bib"
  repository: "/assets/pdfs"
  sort_by: "year,month"
  order: "descending"
